name: 'Close Stale Issues'
on: 
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          start-date: '2020-01-01T00:00:00Z' 
          exempt-all-pr-assignees: true
